env: PRODUCTION
ssl: false
api_version: 2.0
port: 8080
db:
  host: learning-platform.coociopk8atc.ap-southeast-1.rds.amazonaws.com
  db_name: cpp_db
  user: postgres
  password: ndtd1234
redis:
  host: cpp-redis.g6floh.ng.0001.apse1.cache.amazonaws.com:6380
  password:
  secret: cppredissecret123
aws:
  access_key_id: 
  secret_access_key:
  region: ap-southeast-1
  cognito:
    cognito_user_pool_id: ap-southeast-1_7VCM3tWTS
    cognito_app_client_id: 1u61tcmqgkcnfu4vn43ca5d4pi
    cognito_app_client_secret: 77f595ashpoas129kknosbs9c4raaapv4l046fulk1gp2nejf2d
  s3:
    bucket_user_assets: learning-platform-bucket
jwt:
  access_secret: cppaccesssecret123
  refresh_secret: cpprefershsecret123
  access_token_exp: 43200
  refresh_token_exp: 86400