version: '3'
services:
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: 'api.giongedu.store'
      VIRTUAL_NETWORK: 'nginx-proxy'
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: 'api.giongedu.store'
      LETSENCRYPT_EMAIL: 'tiendung3719@gmail.com'
  frontend:
    build:
      context: ./fe
    environment:
      VIRTUAL_HOST: 'giongedu.store'
      VIRTUAL_NETWORK: 'nginx-proxy'
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: 'giongedu.store'
      LETSENCRYPT_EMAIL: 'tiendung3719@gmail.com'
networks:
  default:
    external:
      name: production1_network